- name: Add application user
  ansible.builtin.user:
    name: roboshop

- name: Delete old App dir
  ansible.builtin.file:
    path: /app
    state: absent


- name: create App dir
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and extract app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ app_name }}-v3.zip
    dest: /app
    remote_src: yes

